In [2]:
import numpy as np
from matplotlib import pyplot as plt

In [4]:
def f(y):
    F_dotx = 10 * (y[1] - y[0])
    F_doty = y[0] * (28 - y[2]) - y[1]
    F_dotz = y[0] * y[1] - (8/3) * y[2]
    return np.array([F_dotx, F_doty, F_dotz]).reshape(3,1)

In [12]:
print(f(np.array([1,0,0]).reshape(3,1)))

print(np.array([1,0,0]).reshape(3,1) + 0.5 * 0.0005 * f(np.array([1,0,0]).reshape(3,1)))

print(f(np.array([1,0,0]).reshape(3,1) + 0.5 * 0.0005 * f(np.array([1,0,0]).reshape(3,1))))

print(np.array([1,0,0]).reshape(3,1) + 0.0005 * f(np.array([1,0,0]).reshape(3,1) + 0.5 * 0.0005 * f(np.array([1,0,0]).reshape(3,1))))

[[-10.]
 [ 28.]
 [  0.]]
[[0.9975]
 [0.007 ]
 [0.    ]]
[[-9.9050e+00]
 [ 2.7923e+01]
 [ 6.9825e-03]]
[[9.950475e-01]
 [1.396150e-02]
 [3.491250e-06]]


In [14]:
def f1(x, y, z):
    return 10 * (y - x)

def f2(x, y, z):
    return x * (28 - z) - y

def f3(x, y, z):
    return x * y - (8/3) * z

In [16]:
x = 1
y = 0
z = 0

In [ ]:
def mE(x,y,z,f1,f2,f3):
    p1 = x + 0.0005 * f1(x + 0.5 * 0.0005 * f1(x,y,z), y + 0.5 * 0.0005 * f2(x,y,z), z + 0.5 * 0.0005 * f3(x,y,z))
    p2 = y + 0.0005 * f2(x + 0.5 * 0.0005 * f1(x,y,z), y + 0.5 * 0.0005 * f1(x,y,z), z + 0.5 * 0.0005 * f1(x,y,z))
    p3 = z + 0.0005 * f2(x + 0.5 * 0.0005 * f1(x,y,z), y + 0.5 * 0.0005 * f1(x,y,z), z + 0.5 * 0.0005 * f1(x,y,z))