Group members:

    Mathias Dåsvand,
    
    Ola Rasmussen,
    
    Frida Sogge Steimoeggen

In [36]:
import autograd.numpy as np
from autograd import grad, jacobian
from matplotlib import pyplot as plt

In [50]:
def F(A1,A0,b,g):
    
    row1 = -b * ((A0[0] + A1[0])/2) * ((A0[1] + A1[1])/2)
    row2 = b * ((A0[0] + A1[0])/2) * ((A0[1] + A1[1])/2) - g * ((A0[1] + A1[1])/2)
    row3 = g * ((A0[1] + A1[1])/2)
    
    return np.array([row1, row2, row3])

def f(A1,A0,b,g,F,h):
    return A1 - A0 - h * F(A1,A0,b,g)

def jacobian(A1,A0,b,g,h):
    r11 = 1 + h * b * ((A0[1] + A1[1])/4)
    r12 = h * b * ((A0[0] + A1[0])/4)
    r13 = 0
    row1 = np.array([r11,r12,r13])
    r21 = -h * b * ((A0[1] + A1[1])/4)
    r22 = -h * b * ((A0[0] + A1[0])/4) - g * 0.5
    r23 = 0
    row2 = np.array([r21,r22,r23])
    r31 = 0
    r32 = h * g * 0.5
    r33 = 1
    row3 = np.array([r31,r32,r33])
    
    return np.array([row1,row2,row3])

In [52]:
def newton(A1,A0,f,F,b,g,h,jacobian):
    for i in range(1000):
        x = A1
        for j in range(25):
            x = x - np.dot(np.linalg.inv(jacobian(x,A0,b,g,h)),(f(x,A0,b,g,F,h)))
        x = A0 + h * F(x,A0,b,g)
        A0 = x
    return x
        # while np.linalg.norm(x1 - x0) > 0.01:
            # x0 = f(A1,A0,b,g,F,h)
            
            
            
            # x1 = f(A1,A0,b,g,F,h)

In [53]:
A1 = np.array([0,0,0])
A0 = np.array([0.99,0.01,0])
b = 1
g = 1
h = 0.001

print(f(A1,A0,b,g,F,h))
print(jacobian(A1,A0,b,g,h))

# print(np.linalg.inv(jacobian(f(A1,A0,b,g,F,h))))

print(newton(A1,A0,f,F,1,1,0.001,jacobian))

# print(A1 - np.dot(np.linalg.inv(jacobian(A1,A0,b,g,h)),(f(A1,A0,b,g,F,h))))

[-9.89997525e-01 -9.99747500e-03 -5.00000000e-06]
[[ 1.0000025e+00  2.4750000e-04  0.0000000e+00]
 [-2.5000000e-06 -5.0024750e-01  0.0000000e+00]
 [ 0.0000000e+00  5.0000000e-04  1.0000000e+00]]


LinAlgError: Singular matrix